# Generated by Django 4.2.6 on 2023-10-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_secret', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='hash',
        ),
        migrations.AddField(
            model_name='secret',
            name='is_code_frase',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='secret',
            name='code_frase',
            field=models.CharField(max_length=64, verbose_name='хэш'),
        ),
    ]
