# Generated by Django 4.2.6 on 2023-10-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_secret', '0002_remove_secret_hash_secret_is_code_frase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='code_frase',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='хэш'),
        ),
    ]
