# Generated by Django 4.2.6 on 2023-10-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_secret', '0004_alter_secret_is_code_frase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ссылка'),
        ),
    ]
