# Generated by Django 4.2.6 on 2023-10-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_secret', '0006_rename_code_frase_secret_code_phrase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='time_to_delete',
            field=models.DateTimeField(default='2023-10-29 14:00:38.974649', verbose_name='время удаления'),
            preserve_default=False,
        ),
    ]
