# Generated by Django 4.2.6 on 2023-10-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_secret', '0007_secret_time_to_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='time_to_delete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаления'),
        ),
    ]
