# Generated by Django 4.2.6 on 2023-10-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_secret', '0009_rename_ciphertext_secret_secret_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='secret_text',
            field=models.TextField(verbose_name='секретный текст'),
        ),
    ]
